export const MonthMapper = new Map<number, string>();
MonthMapper.set(0, "ЯНВ");
MonthMapper.set(1, "ФЕВ");
MonthMapper.set(2, "МАР");
MonthMapper.set(3, "АПР");
MonthMapper.set(4, "МАЯ");
MonthMapper.set(5, "ИЮН");
MonthMapper.set(6, "ИЮЛ");
MonthMapper.set(7, "АВГ");
MonthMapper.set(8, "СЕН");
MonthMapper.set(9, "ОКТ");
MonthMapper.set(10, "НОЯБ");
MonthMapper.set(11, "ДЕК");